config/routes.rb
CognitiveWalkthroughHelper::Application.routes.draw do
  resources :walkthroughs do
    member do
      get 'summary'
      get 'report'
    end
  
    resources :tasks, :only => [:index, :create, :new]
  end
  
  resources :tasks, :except => [:index, :create, :new] do
    resources :user_actions, :only => [:index, :create, :new]
  end
  
  resources :user_actions, :except => [:index, :create, :new]
  
  devise_for :users
  
  root to: 'walkthroughs#index'
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :walkthrough
  has_many :user_actions, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_action.rb
class UserAction < ActiveRecord::Base
  belongs_to :task
end

app/models/walkthrough.rb
class Walkthrough < ActiveRecord::Base
  has_many :tasks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :authenticate_user!
  
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :set_walkthrough, only: [:index, :new, :create]

  # GET /tasks
  def index
    @tasks = @walkthrough.tasks
  end

  # GET /tasks/1
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  def create
    @task = Task.new(task_params.merge({:walkthrough_id => @walkthrough.id}))

    if @task.save
      redirect_to @task, notice: 'Task was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /tasks/1
  def update
    if @task.update(task_params)
      redirect_to @task, notice: 'Task was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /tasks/1
  def destroy
    @task.destroy
    redirect_to walkthrough_tasks_url(@task.walkthrough), notice: 'Task was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end
    
    def set_walkthrough
      @walkthrough = Walkthrough.find(params[:walkthrough_id])
    end

    # Only allow a trusted parameter "white list" through.
    def task_params
      params.require(:task).permit(:description)
    end
end

app/controllers/user_actions_controller.rb
class UserActionsController < ApplicationController
  before_filter :authenticate_user!
  
  before_action :set_user_action, only: [:show, :edit, :update, :destroy]
  before_action :set_task, only: [:index, :new, :create]

  # GET /user_actions
  def index
    @user_actions = @task.user_actions
  end

  # GET /user_actions/1
  def show
  end

  # GET /user_actions/new
  def new
    @user_action = UserAction.new
  end

  # GET /user_actions/1/edit
  def edit
  end

  # POST /user_actions
  def create
    @user_action = UserAction.new(user_action_params.merge({:task_id => @task.id}))

    if @user_action.save
      redirect_to @user_action, notice: 'User action was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /user_actions/1
  def update
    if @user_action.update(user_action_params)
      redirect_to @user_action, notice: 'User action was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /user_actions/1
  def destroy
    @user_action.destroy
    redirect_to task_user_actions_url(@user_action.task), notice: 'User action was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_action
      @user_action = UserAction.find(params[:id])
    end
    
    def set_task
      @task = Task.find(params[:task_id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_action_params
      params.require(:user_action).permit(:task_id, :description, :system_response_description, :question_one_is_true,
                                          :question_one_explanation, :question_two_is_true, :question_two_explanation,
                                          :question_three_is_true, :question_three_explanation, :question_four_is_true,
                                          :question_four_explanation, :additional_explanation)
    end
end

app/controllers/walkthroughs_controller.rb
class WalkthroughsController < ApplicationController
  before_filter :authenticate_user!
  
  before_action :set_walkthrough, only: [:show, :edit, :update, :destroy, :summary, :report]

  # GET /walkthroughs
  def index
    @walkthroughs = Walkthrough.all
  end

  # GET /walkthroughs/1
  def show
  end

  # GET /walkthroughs/new
  def new
    @walkthrough = Walkthrough.new
  end

  # GET /walkthroughs/1/edit
  def edit
  end

  # POST /walkthroughs
  def create
    @walkthrough = Walkthrough.new(walkthrough_params)

    if @walkthrough.save
      redirect_to @walkthrough, notice: 'Walkthrough was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /walkthroughs/1
  def update
    if @walkthrough.update(walkthrough_params)
      redirect_to @walkthrough, notice: 'Walkthrough was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /walkthroughs/1
  def destroy
    @walkthrough.destroy
    redirect_to walkthroughs_url, notice: 'Walkthrough was successfully destroyed.'
  end
  
  def summary
  end
  
  def report
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_walkthrough
      @walkthrough = Walkthrough.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def walkthrough_params
      params.require(:walkthrough).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def humanize_boolean(boolean)
    boolean ? 'Yes' : 'No' unless boolean == nil
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/user_actions_helper.rb
module UserActionsHelper
end

app/helpers/walkthroughs_helper.rb
module WalkthroughsHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Cognitive Walkthrough Helper" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Cognitive Walkthrough Helper" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= bootstrap_form_for [@walkthrough, @task] do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.form_group do %>
    <%= f.text_area :description %>
  <% end %>

  <%= f.form_group do %>
    <%= f.submit "Save" %>
  <% end %>
  
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', walkthrough_tasks_path(@task.walkthrough) %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table class="table">
  <thead>
    <tr>
      <th>Description</th>
      <th>Actions</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.description %></td>
        <td><%= link_to task.user_actions.count, task_user_actions_path(task) %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Task', new_walkthrough_task_path(@walkthrough) %> |
<%= link_to 'Back', walkthroughs_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', walkthrough_tasks_path(@walkthrough) %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', walkthrough_tasks_path(@task.walkthrough) %>

app/views/user_actions/_form.html.erb
<%= bootstrap_form_for [@task, @user_action] do |f| %>
  <% if @user_action.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_action.errors.count, "error") %> prohibited this user_action from being saved:</h2>

      <ul>
      <% @user_action.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.form_group do %>
    <%= f.text_area :description %>
  <% end %>
  
  <%= f.form_group do %>
    <%= f.text_area :system_response_description %>
  <% end %>
  
  <%= f.form_group do %>
    <strong>Is the effect of the action the same as the user's goal at that point?</strong> <br />
    <em>Each user action will have a specific effect within the system. Is this effect the same
      as what the user is trying to achieve at this point? For example, if the effect of the action is tosave a
      document, is 'saving a document' what the user wants to do?</em>
    <%= f.radio_button :question_one_is_true, true, label: 'Yes' %>
    <%= f.radio_button :question_one_is_true, false, label: 'No' %>
    <%= f.text_area :question_one_explanation, label: 'Success/failure story' %>
  <% end %>
  
  <%= f.form_group do %>
    <strong>Will the users see that the action is available?</strong> <br />
    <em>Will users see the button or menu item, for example, that is used to produce the action? This is not asking
      whether they will recognize that the button is the one they want. This is merely asking whether it is visible to
      them at the time when they will need to use it. Instances where the answer to this question might be 'no' are,
      for example, where a VCR remote control has a covered panel of buttons or where a menu item is hidden away in a
      submenu.</em>
    <%= f.radio_button :question_two_is_true, true, label: 'Yes' %>
    <%= f.radio_button :question_two_is_true, false, label: 'No' %>
    <%= f.text_area :question_two_explanation, label: 'Success/failure story' %>
  <% end %>
  
  <%= f.form_group do %>
    <strong>Once users have found the correct action, will they know it is the one they need?</strong> <br />
    <em>This complements the previous question. It is one thingfor a button or menu item to be visible, but will the
      user recognize that it is the one he is looking for to complete his task? Where the previous questions was
      about the visibility of the action, this one is about whether its meaning and effect are clear.</em>
    <%= f.radio_button :question_three_is_true, true, label: 'Yes' %>
    <%= f.radio_button :question_three_is_true, false, label: 'No' %>
    <%= f.text_area :question_three_explanation, label: 'Success/failure story' %>
  <% end %>
  
  <%= f.form_group do %>
    <strong>After the action is taken, will users understand the feedback they get?</strong> <br />
    <em>If you now assume that the user did manage to achieve the correct action, will he know that he has done so?
      Will the feedback given be sufficient confirmation of what has actually happened? This is the completion of the
      execution-evaluation interaction cycle. In order to determine if they have accomplished their goal, users need
      appropriate feedback.</em>
    <%= f.radio_button :question_four_is_true, true, label: 'Yes' %>
    <%= f.radio_button :question_four_is_true, false, label: 'No' %>
    <%= f.text_area :question_four_explanation, label: 'Success/failure story' %>
  <% end %>
  
  <%= f.form_group do %>
    <%= f.text_area :additional_explanation %>
  <% end %>
  
  <%= f.form_group do %>
    <%= f.submit "Save" %>
  <% end %>
  
<% end %>

app/views/user_actions/edit.html.erb
<h1>Editing Action</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_action %> |
<%= link_to 'Back', task_user_actions_path(@user_action.task) %>

app/views/user_actions/index.html.erb
<h1>Listing Actions</h1>

<table class="table">
  <thead>
    <tr>
      <th>Description</th>
      <th>Question 1</th>
      <th>Question 2</th>
      <th>Question 3</th>
      <th>Question 4</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @user_actions.each do |user_action| %>
      <tr>
        <td><%= user_action.description %></td>
        <td><%= humanize_boolean(user_action.question_one_is_true) %></td>
        <td><%= humanize_boolean(user_action.question_two_is_true) %></td>
        <td><%= humanize_boolean(user_action.question_three_is_true) %></td>
        <td><%= humanize_boolean(user_action.question_four_is_true) %></td>
        <td><%= link_to 'Show', user_action %></td>
        <td><%= link_to 'Edit', edit_user_action_path(user_action) %></td>
        <td><%= link_to 'Destroy', user_action, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Action', new_task_user_action_path(@task) %> |
<%= link_to 'Back', walkthrough_tasks_path(@task.walkthrough) %>

app/views/user_actions/new.html.erb
<h1>New Action</h1>

<%= render 'form' %>

<%= link_to 'Back', task_user_actions_path(@task) %>

app/views/user_actions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Task:</strong>
  <%= @user_action.task_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @user_action.description %>
</p>

<p>
  <strong>System response description:</strong>
  <%= @user_action.system_response_description %>
</p>

<p>
  <strong>Question one is true:</strong>
  <%= humanize_boolean(@user_action.question_one_is_true) %>
</p>

<p>
  <strong>Question one explanation:</strong>
  <%= @user_action.question_one_explanation %>
</p>

<p>
  <strong>Question two is true:</strong>
  <%= humanize_boolean(@user_action.question_two_is_true) %>
</p>

<p>
  <strong>Question two explanation:</strong>
  <%= @user_action.question_two_explanation %>
</p>

<p>
  <strong>Question three is true:</strong>
  <%= humanize_boolean(@user_action.question_three_is_true) %>
</p>

<p>
  <strong>Question three explanation:</strong>
  <%= @user_action.question_three_explanation %>
</p>

<p>
  <strong>Question four is true:</strong>
  <%= humanize_boolean(@user_action.question_four_is_true) %>
</p>

<p>
  <strong>Question four explanation:</strong>
  <%= @user_action.question_four_explanation %>
</p>

<p>
  <strong>Additional explanation:</strong>
  <%= @user_action.additional_explanation %>
</p>

<%= link_to 'Edit', edit_user_action_path(@user_action) %> |
<%= link_to 'Back', task_user_actions_path(@user_action.task) %>

app/views/walkthroughs/_form.html.erb
<%= bootstrap_form_for(@walkthrough) do |f| %>
  <% if @walkthrough.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@walkthrough.errors.count, "error") %> prohibited this walkthrough from being saved:</h2>

      <ul>
      <% @walkthrough.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.form_group do %>
    <%= f.text_area :description %>
  <% end %>
  
  <%= f.form_group do %>
    <%= f.submit 'Save' %>
  <% end %>
<% end %>

app/views/walkthroughs/edit.html.erb
<h1>Editing walkthrough</h1>

<%= render 'form' %>

<%= link_to 'Show', @walkthrough %> |
<%= link_to 'Back', walkthroughs_path %>

app/views/walkthroughs/index.html.erb
<h1>Listing walkthroughs</h1>

<table class="table">
  <thead>
    <tr>
      <th>Description</th>
      <th>Tasks</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @walkthroughs.each do |walkthrough| %>
      <tr>
        <td><%= walkthrough.description %></td>
        <td><%= link_to walkthrough.tasks.count, walkthrough_tasks_path(walkthrough) %></td>
        <td><%= link_to 'Summary', summary_walkthrough_path(walkthrough) %>
        <td><%= link_to 'Report', report_walkthrough_path(walkthrough) %>
        <td><%= link_to 'Edit', edit_walkthrough_path(walkthrough) %></td>
        <td><%= link_to 'Destroy', walkthrough, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Walkthrough', new_walkthrough_path %>

app/views/walkthroughs/new.html.erb
<h1>New walkthrough</h1>

<%= render 'form' %>

<%= link_to 'Back', walkthroughs_path %>

app/views/walkthroughs/report.html.erb
<h1>Walkthrough summary</h1>

<table class="table">
  <tbody>
    <% @walkthrough.tasks.each do |task| %>
      <tr>
        <td colspan="3"><strong>Task: <%= task.description %></strong></td>
      </tr>
      <% task.user_actions.each do |user_action| %>
        <tr>
          <td colspan="3"><em>Action:</em> <%= user_action.description %></td>
        </tr>
        <tr>
          <td colspan="3"><em>System response:</em> <%= user_action.system_response_description %></td>
        </tr>
        <tr>
          <td><em>Is the effect of the action the same as the user's goal at that point?</em></td>
          <td><%= humanize_boolean(user_action.question_one_is_true) %></td>
          <td><%= user_action.question_one_explanation %></td>
        </tr>
        <tr>
          <td><em>Will the users see that the action is available?</em></td>
          <td><%= humanize_boolean(user_action.question_two_is_true) %></td>
          <td><%= user_action.question_two_explanation %></td>
        </tr>
        <tr>
          <td><em>Once users have found the correct action, will they know it is the one they need?</em></td>
          <td><%= humanize_boolean(user_action.question_three_is_true) %></td>
          <td><%= user_action.question_three_explanation %></td>
        </tr>
        <tr>
          <td><em>After the action is taken, will users understand the feedback they get?</em></td>
          <td><%= humanize_boolean(user_action.question_four_is_true) %></td>
          <td><%= user_action.question_four_explanation %></td>
        </tr>
        <tr>
          <td colspan="3"><em>Additional/general comments:</em> <%= user_action.additional_explanation %></td>
        </tr>
        <tr>
          <td colspan="3"></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<%= link_to "Back", walkthroughs_path %>

app/views/walkthroughs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @walkthrough.description %>
</p>

<%= link_to 'Edit', edit_walkthrough_path(@walkthrough) %> |
<%= link_to 'Back', walkthroughs_path %>

app/views/walkthroughs/summary.html.erb
<h1>Walkthrough summary</h1>

<table class="table">
  <thead>
    <tr>
      <th>Task</th>
      <th>Action</th>
      <th>Question 1</th>
      <th>Question 2</th>
      <th>Question 3</th>
      <th>Question 4</th>
    </tr>
  </thead>
  
  <tbody>
    <% @walkthrough.tasks.each do |task| %>
      <% task.user_actions.each_with_index do |user_action, index| %>
        <tr>
          <td>
            <% if index == 0 %>
              <%= task.description %>
            <% end %>
          </td>
          <td><%= user_action.description %></td>
          <td><%= humanize_boolean(user_action.question_one_is_true) %></td>
          <td><%= humanize_boolean(user_action.question_two_is_true) %></td>
          <td><%= humanize_boolean(user_action.question_three_is_true) %></td>
          <td><%= humanize_boolean(user_action.question_four_is_true) %></td>
        <tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<%= link_to "Back", walkthroughs_path %>